// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package livelog

import "github.com/taskcluster/taskcluster-worker/runtime"

type (
	// LiveLog config
	config struct {

		// Configuration options for the live task log.
		Livelog struct {

			// Location to store the live task log artifact.
			Location string `json:"location"`
		} `json:"livelog"`
	}
)

var configSchema = func() runtime.CompositeSchema {
	schema, err := runtime.NewCompositeSchema(
		"config",
		`
		{
		  "$schema": "http://json-schema.org/draft-04/schema#",
		  "additionalProperties": false,
		  "description": "LiveLog config",
		  "properties": {
		    "livelog": {
		      "description": "Configuration options for the live task log.",
		      "properties": {
		        "location": {
		          "description": "Location to store the live task log artifact.",
		          "title": "Live Log Location",
		          "type": "string"
		        }
		      },
		      "title": "Live Log Configuration",
		      "type": "object"
		    }
		  },
		  "title": "Config",
		  "type": "object"
		}
		`,
		true,
		func() interface{} {
			return &config{}
		},
	)
	if err != nil {
		panic(err)
	}
	return schema
}()
